CREATE TABLE IF NOT EXISTS `ws_tests_running` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `USER_ID` INT DEFAULT NULL,
  `TIME` TIMESTAMP,
  `DURATION` INT
);
CREATE TABLE IF NOT EXISTS `ws_tests_test_report` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `RUNNING_ID` INT NOT NULL,
  `SUCCESS` INT(1) DEFAULT 0,
  `TEST_ID` INT,
  `STATE` VARCHAR(20),
  `DURATION` INT,
  `MESSAGE` TEXT DEFAULT NULL,
  `DATA` TEXT DEFAULT NULL,
  `CALL_STACK` TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `ws_tests_test` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NAME` VARCHAR (100) NOT NULL,
  `LABELS` TEXT,
  `DESCRIPTION` TEXT DEFAULT NULL,
  `PREPARATION` VARCHAR (64) DEFAULT NULL,
  `PREPARATION_DATA` TEXT DEFAULT NULL,
  `ALGORITHM` TEXT DEFAULT NULL,
  `RESULT` TEXT DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS `ws_tests_label` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CODE` VARCHAR (100) NOT NULL,
  `NAME` VARCHAR (100) NOT NULL
);